### ISSUE TITLE
Cannot install extension due to missing icons/ folder 

### ISSUE THREAD

**Issue by JukMR** [qequ/youtube-comments-timestamps#2]
![image](https://github.com/qequ/youtube-comments-timestamps/assets/26848541/4c64304a-218c-4779-941e-a78908be635b)

**Comment by qequ** [comment]
thanks JUK, can you take care of the issue?

**Comment by JukMR** [comment]
Ok! Let's pick an icon for this extension.. What about this?

![DALL·E 2023-11-13 21 12 34 - Icon of YouTube with a twist_ Instead of the usual play button in the center, there's a classic timer  The iconic red and white color scheme of YouTub](https://github.com/qequ/youtube-comments-timestamps/assets/26848541/5938855d-c8fe-4880-8026-a5ed0cbda451)

**Comment by qequ** [comment]
i love it Juk :+1:

**Comment by JukMR** [comment]
The icons seems to be fixed, but now the `popup.html` file seems to be missing. Can you add it @qequ or should i open a new issue for this?

**Comment by qequ** [comment]
Pls open a new issue for this Juk :+1:

**Comment by qequ** [comment]
closed due to PR #3
