### ISSUE TITLE
Missing `popup.html` when extension is selected

### ISSUE THREAD

**Issue by JukMR** [qequ/youtube-comments-timestamps#4]
![image](https://github.com/qequ/youtube-comments-timestamps/assets/26848541/90a12d38-e089-4a7a-bc21-4d53a7574fe0)
![image](https://github.com/qequ/youtube-comments-timestamps/assets/26848541/e151152c-04f7-4c79-a98f-f73984dc25af)

**Comment by qequ** [comment]
can you handle this too Juk?

**Comment by qequ** [comment]
added popup
